name: Publish nestjs-async-lock

on:
  push:
    branches:
      - main
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tawandotorg'

      # Install root dependencies
      - run: npm ci

      # Install nx globally
      - run: npm install -g nx

      # Bump version in the package
      - name: Bump version
        run: |
          cd nestjs-async-lock
          npm version patch --no-git-tag-version

      # Update lockfile and install dependencies after version bump
      - run: npm install

      # Build the package
      - run: nx build nestjs-async-lock

      # Publish the package
      - name: Publish to npm
        run: |
          cd dist/nestjs-async-lock
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}